# Generated by Django 6.0 on 2026-01-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_pedido_telefono_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='¿Disponible para la venta?'),
        ),
    ]
