# Generated by Django 6.0.6 on 2026-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="cantidad",
            new_name="existencia",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="descripcion",
        ),
    ]
