# Generated by Django 6.0.6 on 2026-06-15 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("contacto", models.EmailField(max_length=254, unique=True)),
                ("pais", models.CharField(default="Ecuador", max_length=80)),
            ],
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["nombre"], "verbose_name_plural": "Categorías"},
        ),
        migrations.AddField(
            model_name="categoria",
            name="activa",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="categoria",
            name="creada_en",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categoria",
            name="codigo",
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("existencias", models.PositiveIntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="inventario.categoria",
                    ),
                ),
                (
                    "proveedores",
                    models.ManyToManyField(
                        blank=True, related_name="productos", to="inventario.proveedor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso_kg", models.DecimalField(decimal_places=2, max_digits=6)),
                ("dimensiones", models.CharField(blank=True, max_length=50)),
                ("garantia_meses", models.PositiveIntegerField(default=12)),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha_tecnica",
                        to="inventario.producto",
                    ),
                ),
            ],
        ),
    ]
