# Generated by Django 5.1.1 on 2026-06-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_alter_categoria_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("pais", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("correo", models.CharField(max_length=70)),
                ("telefono", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Disco",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("precio", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                (
                    "artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.artista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad", models.IntegerField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.cliente",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.AddField(
            model_name="disco",
            name="genero",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.genero"
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="disco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventario.disco"
            ),
        ),
    ]
