# Generated by Django 6.0.6 on 2026-06-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0002_proveedor_alter_categoria_options_categoria_activa_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=10)),
                ("direccion", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pedido", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="venta_de_atre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                ("direccion", models.DecimalField(decimal_places=2, max_digits=20)),
                ("pedido", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
