# Generated by Django 6.0.6 on 2026-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_categoria_id_alter_fichatecnica_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnica",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
