# Generated by Django 5.1.1 on 2026-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario",
            "0003_artista_cliente_disco_genero_venta_delete_categoria_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(),
        ),
    ]
