{
    'name': "Comida",
    'version': '1.0',
    'summary': "Gestión de comidas",
    'description': "Módulo para gestionar comidas con estados y cantidades.",
    'author': "DANNY",
    'category': 'Custom',
    'depends': ['base'],
    'data': [
        'views/comida_views.xml',
    ],
    'installable': True,
    'application': True,  # Esto hace que el módulo aparezca en el panel de Aplicaciones
}
# -*- coding: utf-8 -*-
{
    "name": "Comida",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base"],
    "data": [
    "security/ir.model.access.csv",
    "views/comida_views.xml"
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}