[options]
; This is the password that allows database operations:
admin_passwd = aadmin123
db_host = localhost
db_port = 5432
db_user = odoo
db_password = admin123
addons_path = /home/coqueta/Documentos/Semestre2/Programacion/Odoo_Mejorar/ProgII_UTE202601/odoo-19.0/odoo/addons,/home/coqueta/Documentos/Semestre2/Programacion/Odoo_Mejorar/ProgII_UTE202601/odoo/custom-addons
; Si usas proxy
; proxy_mode = True
; Log settings
;logfile = /home/coqueta/Documentos/Semestre2/Programacion/Odoo_Mejorar/ProgII_UTE202601/odoo.log
log_level = info

