[options]
; This is the password that allows database operations:
admin_passwd = admin123
db_host = localhost
db_port = 5432
db_user = odoo
db_password = admin123
addons_path = /home/alumnos/Trabajo/odoo/estudiante/estudiante/jacome_jandry/odoo-19.0/odoo/addons,/home/alumnos/Trabajo/odoo/estudiante/estudiante/jacome_jandry/odoo-19.0/addons,/home/alumnos/Trabajo/odoo/estudiante/estudiante/jacome_jandry/odoo/custom-addons
; Si usas proxy
; proxy_mode = True
; Log settings
;logfile = /home/alumnos/Trabajo/odoo/estudiante/estudiante/jacome_jandry/odoo.log
log_level = info
