[options]
; This is the password that allows database operations:
admin_passwd = admin123
db_host = localhost
db_port = 5432
db_user = odoo
db_password = aadmin123
addons_path = /home/vboxuser/Odoo/ProgII_UTE202601/odoo-19.0/odoo/addons,/home/vboxuser/Odoo/ProgII_UTE202601/odoo-19.0/addons,/home/vboxuser/Odoo/ProgII_UTE202601/custom-addons
; Si usas proxy
; proxy_mode = True
; Log settings
;logfile = /home/vboxuser/Odoo/ProgII_UTE202601/odoo.log
log_level = info
