# Generated by Django 5.2.15 on 2026-06-18 22:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('registered_on', models.DateField(auto_now_add=True, verbose_name='fecha de registro')),
                ('is_student', models.BooleanField(default=False, verbose_name='es estudiante')),
            ],
            options={
                'verbose_name': 'asistente',
                'verbose_name_plural': 'asistentes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('summary', models.TextField(verbose_name='resumen')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('banner', models.ImageField(blank=True, upload_to='events/banners/', verbose_name='banner')),
                ('program_pdf', models.FileField(blank=True, upload_to='events/programs/', verbose_name='programa PDF')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacidad')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('floor', models.IntegerField(verbose_name='piso')),
                ('seating_capacity', models.PositiveIntegerField(verbose_name='aforo')),
                ('has_projector', models.BooleanField(default=True, verbose_name='tiene proyector')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('bio', models.TextField(verbose_name='biografía')),
                ('photo', models.ImageField(blank=True, upload_to='speakers/photos/', verbose_name='foto')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('rating', models.FloatField(default=0.0, verbose_name='calificación')),
            ],
            options={
                'verbose_name': 'ponente',
                'verbose_name_plural': 'ponentes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('abstract', models.TextField(verbose_name='resumen')),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20, verbose_name='nivel')),
                ('scheduled_at', models.DateTimeField(verbose_name='programado para')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('duration', models.DurationField(verbose_name='duración')),
                ('is_keynote', models.BooleanField(default=False, verbose_name='keynote')),
                ('max_seats', models.PositiveIntegerField(verbose_name='plazas máximas')),
                ('recording_url', models.URLField(blank=True, verbose_name='grabación')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event', verbose_name='evento')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='events.room', verbose_name='sala')),
                ('speakers', models.ManyToManyField(related_name='sessions', to='events.speaker', verbose_name='ponentes')),
            ],
            options={
                'verbose_name': 'sesión',
                'verbose_name_plural': 'sesiones',
                'ordering': ['scheduled_at'],
                'unique_together': {('event', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name='años de experiencia')),
                ('website', models.URLField(blank=True, verbose_name='sitio web')),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='events.speaker', verbose_name='ponente')),
            ],
            options={
                'verbose_name': 'perfil de ponente',
                'verbose_name_plural': 'perfiles de ponente',
                'ordering': ['speaker'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmado')),
                ('seat_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de asiento')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='monto pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.attendee', verbose_name='asistente')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.session', verbose_name='sesión')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-created_at'],
                'unique_together': {('attendee', 'session')},
            },
        ),
    ]
