# Generated by Django 5.2.15 on 2026-06-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='clave')),
                ('value', models.JSONField(verbose_name='valor')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
                'ordering': ['key'],
            },
        ),
    ]
