# -*- coding: utf-8 -*-
{
    "name": "Arte",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Xavier Esmeralda',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',


    "depends": ["base"],


    "data": [
    "security/ir.model.access.csv",
    "views/pedido.xml",
    "views/factura.xml",
    "views/menu.xml"
    ],


    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True

}
