# -*- coding: utf-8 -*-
{
    "name": "Odoomaty Proyecto Puesto De Comida",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base"],
    "data": [
        "security/comida_security.xml",
        "security/ir.model.access.csv",
        "views/odoomaty_proyecto_puesto_de_comida_views.xml"
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}