# Generated by Django 6.0.6 on 2026-07-04 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canchas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cancha', models.CharField(max_length=100)),
                ('Costo_por_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Por Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('s_nombre', models.CharField(blank=True, max_length=100, verbose_name='Segundo nombre')),
                ('apellido', models.CharField(max_length=100)),
                ('s_apellido', models.CharField(blank=True, max_length=100, verbose_name='Segundo apellido')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_p', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto')),
                ('precio_p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario')),
                ('cantidad_p', models.IntegerField(blank=True, null=True, verbose_name='Cantidad del producto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_p', models.CharField(max_length=100)),
                ('costo_p', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del paquete')),
                ('descripcion', models.TextField(verbose_name='Descripcion del paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservo', models.BooleanField(default=False, verbose_name='Si llego')),
                ('nombre_cli', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangov1.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov1.gestion_reserva')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov1.inventario')),
            ],
        ),
        migrations.AddField(
            model_name='gestion_reserva',
            name='productos_de_consumo',
            field=models.ManyToManyField(through='djangov1.DetalleConsumo', to='djangov1.inventario', verbose_name='Productos consumidos'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('numero_Rs', models.AutoField(primary_key=True, serialize=False)),
                ('Hora_ll', models.TimeField(verbose_name='Hora de llegada')),
                ('Hora_Sa', models.TimeField(verbose_name='Hora de salida')),
                ('Pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_ju', models.IntegerField(verbose_name='Numero de jugadores')),
                ('nota', models.TextField(verbose_name='Nota extra de la reservacion')),
                ('Canchas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangov1.canchas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov1.cliente')),
                ('paquete_incluido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangov1.paquete')),
            ],
        ),
        migrations.AddField(
            model_name='gestion_reserva',
            name='canchas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov1.reserva'),
        ),
    ]
