# Generated by Django 6.0.6 on 2026-07-04 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangov2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleconsumo',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov2.gestion_reserva'),
        ),
        migrations.AlterField(
            model_name='detalleconsumo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov2.inventario'),
        ),
        migrations.AlterField(
            model_name='gestion_reserva',
            name='canchas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov2.reserva'),
        ),
        migrations.AlterField(
            model_name='gestion_reserva',
            name='nombre_cli',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djangov2.cliente'),
        ),
        migrations.AlterField(
            model_name='gestion_reserva',
            name='productos_de_consumo',
            field=models.ManyToManyField(through='djangov2.DetalleConsumo', to='djangov2.inventario', verbose_name='Productos consumidos'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Canchas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangov2.canchas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangov2.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paquete_incluido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangov2.paquete'),
        ),
    ]
