# Generated by Django 6.0 on 2026-01-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('PAN', 'Panadería'), ('PAS', 'Pastelería'), ('GAL', 'Galletería')], default='PAN', max_length=3),
        ),
    ]
