# Generated by Django 6.0 on 2026-01-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_pedido_options_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('PAN', 'Panadería'), ('PAS', 'Pastelería'), ('GAL', 'Galletería'), ('POS', 'Postres')], default='PAN', max_length=3),
        ),
    ]
