# Generated by Django 6.0.6 on 2026-06-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Actores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('sala', models.CharField(max_length=100)),
                ('entradas_disponibles', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Funciones',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion_min', models.IntegerField()),
                ('fecha_estreno', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Obras',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('asiento', models.CharField(max_length=20)),
                ('fecha_compra', models.DateField()),
                ('confirmado', models.BooleanField(default=True)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='djangov1.funcion')),
            ],
            options={
                'verbose_name_plural': 'Boletos',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.AddField(
            model_name='funcion',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='djangov1.obra'),
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje', models.CharField(max_length=150)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='djangov1.actor')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='djangov1.obra')),
            ],
            options={
                'verbose_name_plural': 'Participaciones',
                'ordering': ['obra', 'actor'],
            },
        ),
    ]
