# -*- coding: utf-8 -*-
{
    "name": "PLASTINEW",
    "version": "19.0.1.0.0",
    "category": "Manufacturing",
    "summary": "Gestion de empresa de productos plasticos",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Alisson_Ormaza',
    "maintainer": "",
    "website": 'https://www.plastinew.com',
    "depends": ["base"],
    "data": [
          'security/plasticos_group.xml',      
          'security/plasticos_rule.xml',       
          'security/ir.model.access.csv',       
          'views/cliente_views.xml',
          'views/venta_views.xml',
          'views/inventario_views.xml',
          'views/produccion_views.xml',
          'views/menu_views.xml',
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}