{
    'name': 'KodigoWasi',
    'version': '1.0',
    'summary': 'Talleres de programación con Railway Oriented Programming',
    'author': 'MashiCode',
    'depends': ['base'],
    'data': [
        'security/kodigo_wasi_groups.xml',
        'security/ir.model.access.csv',
        'views/kw_taller_views.xml',
        'views/kw_participante_views.xml',
        'views/kw_instructor_views.xml',
        'views/kw_sesion_views.xml',
        'views/kw_inscripcion_views.xml',
        'views/kw_pago_views.xml',
        'views/kodigo_wasi_menus_actions.xml',
        # 'views/kodigo_wasi_menus.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
