# Generated by Django 6.0.7 on 2026-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangov1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
