# Generated by Django 6.0.6 on 2026-06-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangov1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='flor',
            options={'verbose_name': 'Flor', 'verbose_name_plural': 'Flores'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tipoflor',
            options={'verbose_name': 'Tipo Flor', 'verbose_name_plural': 'Tipo Flores'},
        ),
        migrations.RenameField(
            model_name='tipoflor',
            old_name='activa',
            new_name='disponibilidad',
        ),
    ]
