# Generated by Django 5.1.1 on 2026-06-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prestamo",
            old_name="fecha_decolucon",
            new_name="fecha_devolucon",
        ),
    ]
